Repository PowerGridModel/power-grid-model-io, pull requests merged in 2024-02, with the labels that each got.

#221 Pandapower Jupyter example notebook log output fix
  docs/examples/pandapower_example.ipynb
  src/power_grid_model_io/converters/pandapower_converter.py
Labels: improvement

#224 do not fatally crash on pandas 2.1
  tests/conftest.py
  tests/unit/conftest.py
  tests/validation/conftest.py
Labels: bug

#227 Temporary workaround converting Vision 97 file
  src/power_grid_model_io/utils/uuid_excel_cvtr.py
  tests/data/vision/vision_97_en.xlsx
  tests/data/vision/vision_97_en.xlsx.license
  tests/unit/utils/test_uuid_excel_cvtr.py
Labels: feature

#228 Fix the instance id issue when having multiple converter objects
  src/power_grid_model_io/converters/base_converter.py
Labels: bug
