Repository PowerGridModel/power-grid-model-io, pull requests merged in 2025-05, with the labels that each got.

#296 Add trusted publisher
  .github/workflows/ci.yml
Labels: feature

#302 Fix sonar coverage
  .github/workflows/ci.yml
  .gitignore
  pyproject.toml
  sonar-project.properties
Labels: dependencies

#303 dependencies: compatibility pandapower 2 and 3 and numpy 1 and 2
  pyproject.toml
  src/power_grid_model_io/converters/pandapower_converter.py
  tests/data/pandapower/pp_v2_net_3ph_output.json
  tests/data/pandapower/pp_v2_net_3ph_output.json.license
  tests/data/pandapower/pp_v2_net_output.json
  tests/data/pandapower/pp_v2_net_output.json.license
  tests/unit/converters/test_pandapower_converter_input.py
  tests/utils.py
  tests/validation/converters/test_pandapower_converter_output.py
Labels: dependencies, improvement

#304 dependencies: dependabot for pip
  .github/dependabot.yml
Labels: dependencies
